### PR TITLE
Update some dependencies

### PR DESCRIPTION
**Pull request by koushiro**
Signed-off-by: koushiro <koushiro.cqx@gmail.com>

Close #101

### CODE REVIEW

**Comment by koushiro** [comment]
@sorpaas could you merge this PR and release a new version?
I wanna to update the substrate version of frontier to the latest.

**Comment by sorpaas** [comment]
Sorry I missed this. Can you resolve the conflict and bump version number to 0.35?

**Comment by koushiro** [comment]
@sorpaas PTAL

**Comment by tgmichel** [comment]
@koushiro can you fix the tests? We also want this to be released asap. Thank you.

**Comment by koushiro** [comment]
CI is terrible, `evm`'s tests depend on `evm-jsontests` (belongs to another [repository](https://github.com/rust-blockchain/evm-tests)), which actually depends on the `evm` git submodule.

**Comment by tgmichel** [comment]
Just open a PR on `evm-tests`, hopefully that helps to get this through

**Comment by koushiro** [comment]
@sorpaas Once the PR https://github.com/rust-blockchain/evm-tests/pull/13 is merged, CI will pass, see https://github.com/koushiro/evm/pull/2 for details

**Pull request merged**
