### PR TITLE
fix depth

### PR DESCRIPTION
**Pull request by ermalkaleci**

### CODE REVIEW

**Comment by ermalkaleci** [comment]
@sorpaas or we can update this https://github.com/rust-blockchain/evm/blob/07ae4451bb1d8d1cc81e5e07685691e68220a7d2/src/executor/stack/executor.rs#L639
to be `if depth >= self.config.call_stack_limit {`

**Comment by sorpaas** [comment]
> to be if depth >= self.config.call_stack_limit {

Yeah I'd prefer that. I'm surprised this isn't caught by jsontests though.

**Comment by ermalkaleci** [comment]
> > to be if depth >= self.config.call_stack_limit {
> 
> Yeah I'd prefer that. I'm surprised this isn't caught by jsontests though.

there are 2 tests actually but they're skipped. one in st_revert and one in st_create2

**Comment by ermalkaleci** [comment]
@sorpaas `call_inner` is checking depth after entering substate which will set depth to `Some(0)` but `create_inner` is checking before and depth is `None`, that's where the problem is

**Pull request closed without merging**
